In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
# train test split 
from sklearn.model_selection import train_test_split

In [6]:
df = pd.read_csv("preprocessed_data.csv")
df

Unnamed: 0                                 Job Title  ... tableau azure
0              0                            Data Scientist  ...       0     1
1              1                             Web Developer  ...       0     0
2              2                              Data Analyst  ...       1     0
3              3                    Database Administrator  ...       0     0
4              4                             iOS Developer  ...       0     0
...          ...                                       ...  ...     ...   ...
4912        4912                       Front End Developer  ...       0     0
4913        4913              Sr Software Quality Engineer  ...       0     0
4914        4914                      Lead Mobile Engineer  ...       0     0
4915        4915  Cloud Infrastructure Engineer (SRE/Java)  ...       0     0
4916        4916        Development Chapter Lead in Retail  ...       0     0

[4917 rows x 35 columns]

In [7]:
df.columns

Index(['Unnamed: 0', 'Job Title', 'Salary Estimate', 'Job Description',
       'Rating', 'Company Name', 'Location', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'hourly',
       'employer_provided', 'min_salary', 'max_salary', 'avg_salary',
       'job_state', 'age', 'job_title_tag', 'seniority', 'desc_len', 'python',
       'R', 'spark', 'aws', 'excel', 'sql', 'django', 'hadoop', 'java', 'db',
       'tableau', 'azure'],
      dtype='object')

In [8]:
df['Job Title'].unique()

array(['Data Scientist', 'Web Developer', 'Data Analyst', ...,
       'Lead Mobile Engineer', 'Cloud Infrastructure Engineer (SRE/Java)',
       'Development Chapter Lead in Retail'], dtype=object)

In [9]:
df_model = df[['Job Title', 'Rating','Company Name', 'Company Name', 'Size',
               'Type of ownership', 'Industry', 'Sector', 'Revenue', 'hourly', 'employer_provided',
               'avg_salary', 'job_state', 'age',
               'job_title_tag', 'seniority', 'desc_len', 'python', 'R', 'spark', 'aws',
               'excel', 'sql', 'django', 'hadoop', 'java', 'db', 'tableau', 'azure']]
               

In [10]:
dummy_df = pd.get_dummies(df_model)

X = dummy_df.drop('avg_salary', axis =1)
y = dummy_df.avg_salary.values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=24)

In [11]:
df['Job Description'].map(lambda x: len(x)).mean()

1031.6672767947937

In [36]:
df['avg_salary'].mean()

86.35946715476916

## RNN - GRU


In [37]:

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.layers import LSTM, Activation, Dense, Dropout, Input, Embedding, BatchNormalization, GRU

In [47]:

max_words = 10000
max_len = 1000
tok = Tokenizer(num_words=max_words)
tok.fit_on_texts(df['Job Description'])
sequences = tok.texts_to_sequences(df['Job Description'])
sequences_matrix = sequence.pad_sequences(sequences,maxlen=max_len)

In [113]:
def RNN():
    inputs = Input(name='inputs',shape=[max_len])
    layer = Embedding(max_words,50,input_length=max_len)(inputs)
    layer = GRU(128)(layer)
    layer = Bidirectional(layer)
    # layer = Dropout(0.2)(layer)
    # layer = Dense(64,name='FC2')(layer)
    # layer = Activation('sigmoid')(layer)
    # layer = Dropout(0.2)(layer)
    layer = Dense(1,name='out_layer')(layer)
    layer = Activation('relu')(layer)
    model = Model(inputs=inputs,outputs=layer)
    return model

In [114]:

model = RNN()

model.summary()
model.compile(loss='mse',optimizer=RMSprop(),metrics=['mae', 'mse', 'msle'])

NameError: ignored

In [115]:
model.fit(sequences_matrix,df['avg_salary'],epochs=150,
                    batch_size=256,
                    verbose=1 ,validation_split=0.1)

Epoch 1/150
18/18 [==============================] - 2s 117ms/step - loss: 60.5776 - mae: 4.0615 - mse: 60.5776 - msle: 0.0058 - val_loss: 1093.4685 - val_mae: 24.6548 - val_mse: 1093.4685 - val_msle: 0.2525
Epoch 2/150
18/18 [==============================] - 2s 112ms/step - loss: 59.4960 - mae: 4.0388 - mse: 59.4960 - msle: 0.0057 - val_loss: 1099.2037 - val_mae: 24.9053 - val_mse: 1099.2037 - val_msle: 0.2456
Epoch 3/150
18/18 [==============================] - 2s 110ms/step - loss: 58.9754 - mae: 4.0308 - mse: 58.9754 - msle: 0.0057 - val_loss: 1089.7416 - val_mae: 24.7566 - val_mse: 1089.7416 - val_msle: 0.2485
Epoch 4/150
18/18 [==============================] - 2s 109ms/step - loss: 54.2114 - mae: 3.6356 - mse: 54.2114 - msle: 0.0049 - val_loss: 1099.7091 - val_mae: 24.7008 - val_mse: 1099.7091 - val_msle: 0.2513
Epoch 5/150
18/18 [==============================] - 2s 111ms/step - loss: 55.3328 - mae: 3.8317 - mse: 55.3328 - msle: 0.0053 - val_loss: 1058.8799 - val_mae: 24.2449 

In [120]:

test_sequences = tok.texts_to_sequences(
    ["""We are looking for a full time iOS Software Engineer to join our team in Olathe, KS. In this role, you’ll be responsible for architecting and developing complex software utilized by the suite of Garmin mobile applications. Responsibilities include:
Develop software using Swift and Objective-C
Utilize tools in the software development process such as Git, Gerrit, Bitbucket, Jira, Confluence, Xcode, and Jenkins
Create and implement designs for software components within a larger project"""])
test_sequences_matrix = sequence.pad_sequences(test_sequences,maxlen=max_len)

In [121]:
pred = model.predict(test_sequences_matrix)
pred

array([[107.400795]], dtype=float32)

In [122]:

test_sequences = tok.texts_to_sequences(["""As a Data Scientist Architect you will be applying new and innovative methods to address some of our most important intelligence problems \
What You'll Be Doing:\
Knowledge and experience in designing and implementing AI apps and agents that use the Microsoft Azure Cognitive Services, Azure Bot Service, Azure Cognitive Search, and data storage options \
Analyzing requirements for AI solutions Experience with NoSQL databases Experience with applying Data Science techniques to overhead imagery (computer vision, object detection \
Ability to work autonomously and collaboratively as part of a team to both teach and learn every day"""])
test_sequences_matrix = sequence.pad_sequences(test_sequences,maxlen=max_len)
pred = model.predict(test_sequences_matrix)
pred

array([[67.131035]], dtype=float32)

In [119]:
sequences_matrix[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   